version: '3.9'

services:
  python:
    image: python:3.9-slim
    container_name: python_service
    stdin_open: true
    tty: true

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME:
      MONGO_INITDB_ROOT_PASSWORD:
      MONGO_INITDB_DATABASE: arb

volumes:
  redis-data:
  mongodb_data:
    driver: local
