name: CD

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            cd ./projects/alwaysReelsBot
            git pull origin main
            yarn
            
            timeout 1m yarn prisma migrate deploy
            
            if [ $? -ne 0 ]; then 
              echo "Error prisma migrate dev"
              exit 1
            fi
            
            yarn build