name: CD

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            source ~/.nvm/nvm.sh &&
            nvm use 20 &&
            cd ${{ secrets.PROJECT_PATH}} &&
            git pull origin main &&
            yarn &&
            npx prisma migrate deploy &&
            yarn build
            pm2 restart ${{ secrets.PM2_PROCESS }}