name: CI

on:
  push:
    branches:
      - "**"

jobs:
  install_deps_and_lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

      - name: Yarn lint
        run: yarn lint

  build:
    needs: install_deps_and_lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

      - name: Build application
        run: yarn build