name: CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: check

    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script:  |
            if ${{ github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true) }}; then
              cd ./projects/ARB
              git pull origin main
              yarn
            
              timeout 1m yarn prisma migrate deploy
            
              if [ $? -ne 0 ]; then 
              echo "Error prisma migrate dev"
              exit 1
              fi
            
              yarn build
            fi